rng_seed: 12345
infectiousness_params:
  incubation_shape: 5.807
  incubation_scale: 0.948
  latent_shape: 3.38
  symptomatic_rate: 0.37
  symptomatic_shape: 1.0
  rel_presymptomatic_infectiousness: 2.29
clock:
  subs_rate: 0.001
  relax_rate: True
  subs_rate_sigma: 0.33
  gen_length: 29903
inference:
  num_simulations: 10000
  intermediate_generations: [0,1]
  intermediate_hosts: 10
characterisation:
  genetic_distance_grid:
    max_snp: 10
    step: 1
  temporal_distance_grid:
    max_days: 21
    step: 1
